Repository Konkuk-KUIT/KUIT5_WEB-Frontend, pull requests merged in 2025-03, with the labels that each got.

#4 [1주차] 자기소개 HTML
  week1/junseochoi/index.html
Labels: 최준서

#13 [1주차] 자기소개 HTML
  week1/jung-eon/index.html
Labels: 이정언

#16 [1주차] 자기소개 HTML
  week1/sunghoJo/index.html
Labels: 조성호

#1 [1주차] 자기소개 HTML
  week1/TaekyuAhn/index.html
Labels: 안태규

#3 [1주차] 자기소개 HTML
  week1/lyouxsun/index.html
Labels: 이영선

#6 [1주차] 자기소개 HTML
  week1/jungbeen/index.html
Labels: 이정빈

#8 [1주차] 자기소개 HTML
  week1/GahyunKim/index.html
Labels: 김가현

#10 [1주차] 자기소개 HTML
  week1/FEhwan/myhtml.html
Labels: 이지환

#11 [1주차] 자기소개 HTML
  .github/PULL_REQUEST_TEMPLATE.md
  week1/dongyun/index.html
  week1/turtlehwan/index.html
Labels: 강동윤

#12 [1주차] 자기소개 HTML
  week1/sangh2ee/index.css
  week1/sangh2ee/index.html
Labels: 백상희

#15 [1주차] 자기소개 HTML
  week1/parktaehee/index.css
  week1/parktaehee/index.html
Labels: 박태희

#14 [1주차] 자기소개 HTML
  week1/dohyeonKim/index.css
  week1/dohyeonKim/index.html
Labels: 김도현2732

#7 [1주차]자기소개 HTML
  week1/dhKim/index.html
Labels: 김도현3885

#2 [1주차] 자기 소개 html
  week1/turtlehwan/index.html
Labels: 진은총

#19 [2주차] 당근 클론 코딩
  week2/jung-eon/assets/bx_chat.svg
  week2/jung-eon/assets/chat-img.svg
  week2/jung-eon/assets/expand-arrow.svg
  week2/jung-eon/assets/heart.svg
  week2/jung-eon/assets/home-img.svg
  week2/jung-eon/assets/menu1.svg
  week2/jung-eon/assets/news-img.svg
  week2/jung-eon/assets/notification1.svg
  week2/jung-eon/assets/place-marker-img.svg
  week2/jung-eon/assets/plus-button.svg
  week2/jung-eon/assets/post-header__bottom.svg
  week2/jung-eon/assets/post__img1.svg
  week2/jung-eon/assets/post__img2.svg
  week2/jung-eon/assets/post__img3.svg
  week2/jung-eon/assets/post__img4.svg
  week2/jung-eon/assets/post__img5.svg
  week2/jung-eon/assets/search.svg
  week2/jung-eon/assets/user-img.svg
  week2/jung-eon/index.css
  week2/jung-eon/index.html
Labels: 이정언

#22 [2주차] 당근마켓 클론코딩
  .vscode/settings.json
  week2/dhKim/assets/airpod.jpg
  week2/dhKim/assets/bell.svg
  week2/dhKim/assets/blanche.jpg
  week2/dhKim/assets/chat.svg
  week2/dhKim/assets/chat_bottom.svg
  week2/dhKim/assets/coffeemachine.jpg
  week2/dhKim/assets/expan-arrow.svg
  week2/dhKim/assets/headphone.jpg
  week2/dhKim/assets/heart.svg
  week2/dhKim/assets/home.svg
  week2/dhKim/assets/iphone.jpg
  week2/dhKim/assets/location.svg
  week2/dhKim/assets/menu.svg
  week2/dhKim/assets/my.svg
  week2/dhKim/assets/new.svg
  week2/dhKim/assets/plus.svg
  week2/dhKim/assets/sandwitch.jpg
  week2/dhKim/assets/search.svg
  week2/dhKim/index.html
  week2/dhKim/init.css
  week2/dhKim/style.css
Labels: 김도현3885

#21 [2주차] Blessilvery
  .DS_Store
  week1/.DS_Store
  week2/ecjin/assets/chat.svg
  week2/ecjin/assets/comment.svg
  week2/ecjin/assets/down-chevron.svg
  week2/ecjin/assets/heart.svg
  week2/ecjin/assets/home.svg
  week2/ecjin/assets/kebab.svg
  week2/ecjin/assets/left-chevron copy.svg
  week2/ecjin/assets/left-chevron.svg
  week2/ecjin/assets/menu.svg
  week2/ecjin/assets/news.svg
  week2/ecjin/assets/notification.svg
  week2/ecjin/assets/place-marker.svg
  week2/ecjin/assets/plus.svg
  week2/ecjin/assets/right-chevron.svg
  week2/ecjin/assets/search.svg
  week2/ecjin/assets/share.svg
  week2/ecjin/assets/small_heart.svg
  week2/ecjin/assets/user.svg
  week2/ecjin/assets/vector.svg
  week2/ecjin/assignment.css
  week2/ecjin/assignment.html
  week2/ecjin/index.css
  week2/ecjin/index.html
  week2/ecjin/reset.css
  week2/jinho1011/clone/assets/home.svg
Labels: 진은총

#23 [2주차] 당근 클론코딩
  week2/lyouxsun/assets/black-home.svg
  week2/lyouxsun/assets/bx-chat.svg
  week2/lyouxsun/assets/chat.svg
  week2/lyouxsun/assets/down-chevron.svg
  week2/lyouxsun/assets/heart.svg
  week2/lyouxsun/assets/home.svg
  week2/lyouxsun/assets/kebab.svg
  week2/lyouxsun/assets/left-chevron.svg
  week2/lyouxsun/assets/menu.svg
  week2/lyouxsun/assets/news.svg
  week2/lyouxsun/assets/notification.svg
  week2/lyouxsun/assets/place-marker.svg
  week2/lyouxsun/assets/plus.svg
  week2/lyouxsun/assets/reaction-heart.svg
  week2/lyouxsun/assets/right-chevron.svg
  week2/lyouxsun/assets/search.svg
  week2/lyouxsun/assets/share.svg
  week2/lyouxsun/assets/temperature.svg
  week2/lyouxsun/assets/user.svg
  week2/lyouxsun/assignment/index.css
  week2/lyouxsun/assignment/index.html
  week2/lyouxsun/practice/index.css
  week2/lyouxsun/practice/index.html
  week2/lyouxsun/reset.css
Labels: 이영선

#24 [2주차] 당근마켓 클론코딩
  .vscode/launch.json
  week2/FEhwan/assets/chat.svg
  week2/FEhwan/assets/comment.svg
  week2/FEhwan/assets/expand_arrow.svg
  week2/FEhwan/assets/heart.svg
  week2/FEhwan/assets/home.svg
  week2/FEhwan/assets/menu.svg
  week2/FEhwan/assets/my.svg
  week2/FEhwan/assets/near.svg
  week2/FEhwan/assets/news.svg
  week2/FEhwan/assets/notification.svg
  week2/FEhwan/assets/plus.svg
  week2/FEhwan/assets/post1.svg
  week2/FEhwan/assets/post2.svg
  week2/FEhwan/assets/post3.svg
  week2/FEhwan/assets/post4.svg
  week2/FEhwan/assets/post5.svg
  week2/FEhwan/assets/search.svg
  week2/FEhwan/index.css
  week2/FEhwan/index.html
Labels: 이지환

#25 [2주차] 당근마켓 클론코딩
  .vscode/settings.json
  week2/GahyunKim/assets/arrow.svg
  week2/GahyunKim/assets/chat.svg
  week2/GahyunKim/assets/chatmessage.svg
  week2/GahyunKim/assets/doc.svg
  week2/GahyunKim/assets/happy.svg
  week2/GahyunKim/assets/home.svg
  week2/GahyunKim/assets/image1.svg
  week2/GahyunKim/assets/map.svg
  week2/GahyunKim/assets/menu.svg
  week2/GahyunKim/assets/notification.svg
  week2/GahyunKim/assets/placeMarker.svg
  week2/GahyunKim/assets/plus.svg
  week2/GahyunKim/assets/search.svg
  week2/GahyunKim/assets/speechbubble.svg
  week2/GahyunKim/assets/user.svg
  week2/GahyunKim/assets/userAccount.svg
  week2/GahyunKim/assets/vector1.svg
  week2/GahyunKim/assets/wallet1.svg
  week2/GahyunKim/assets/wallet2.svg
  week2/GahyunKim/assets2/airpods.svg
  week2/GahyunKim/assets2/chat.svg
  week2/GahyunKim/assets2/coffee.svg
  week2/GahyunKim/assets2/heart.svg
  week2/GahyunKim/assets2/perfume.svg
  week2/GahyunKim/assets2/phone.svg
  week2/GahyunKim/assets2/sandwich.svg
  week2/GahyunKim/index.css
  week2/GahyunKim/index.html
  week2/GahyunKim/index2.css
  week2/GahyunKim/index2.html
  week2/GahyunKim/reset.css
Labels: 김가현

#27 [2주차]당근마켓 클론코딩
  week2/jungbeen/clone/assets/airpods.svg
  week2/jungbeen/clone/assets/byredo.svg
  week2/jungbeen/clone/assets/expand-arrow.svg
  week2/jungbeen/clone/assets/heart.svg
  week2/jungbeen/clone/assets/iphone.svg
  week2/jungbeen/clone/assets/menu.svg
  week2/jungbeen/clone/assets/nav-chat.svg
  week2/jungbeen/clone/assets/nav-home.svg
  week2/jungbeen/clone/assets/nav-location.svg
  week2/jungbeen/clone/assets/nav-newspaper.svg
  week2/jungbeen/clone/assets/nav-person.svg
  week2/jungbeen/clone/assets/notification.svg
  week2/jungbeen/clone/assets/page2/answer.svg
  week2/jungbeen/clone/assets/page2/banner-image.svg
  week2/jungbeen/clone/assets/page2/checkmark.svg
  week2/jungbeen/clone/assets/page2/chicken.jpeg
  week2/jungbeen/clone/assets/page2/comment.svg
  week2/jungbeen/clone/assets/page2/companion.svg
  week2/jungbeen/clone/assets/page2/kfc.png
  week2/jungbeen/clone/assets/page2/location.svg
  week2/jungbeen/clone/assets/page2/plus.svg
  week2/jungbeen/clone/assets/page2/smilemark.svg
  week2/jungbeen/clone/assets/sales-chat.svg
  week2/jungbeen/clone/assets/sandwitch.svg
  week2/jungbeen/clone/assets/search.svg
  week2/jungbeen/clone/index.css
  week2/jungbeen/clone/index.html
  week2/jungbeen/clone/page2.css
  week2/jungbeen/clone/page2.html
  week2/jungbeen/clone/reset.css
Labels: 이정빈

#28 [2주차]당근마켓1 클론코딩
  README.md
  week2/dongyun/assets/chatting_icon.svg
  week2/dongyun/assets/expand_arrow.svg
  week2/dongyun/assets/heart_icon.svg
  week2/dongyun/assets/home_btn_icon.svg
  week2/dongyun/assets/location_marker_icon.svg
  week2/dongyun/assets/menu_btn.svg
  week2/dongyun/assets/notification_icon.svg
  week2/dongyun/assets/offer_chat_count_icon.svg
  week2/dongyun/assets/plus_icon.svg
  week2/dongyun/assets/posting_icon.svg
  week2/dongyun/assets/profile_icon.svg
  week2/dongyun/assets/search_btn.svg
  week2/dongyun/assets/villiage_news_icon.svg
  week2/dongyun/dummy_assets/airpot.png
  week2/dongyun/dummy_assets/airpot.svg
  week2/dongyun/dummy_assets/coffeeTool.svg
  week2/dongyun/dummy_assets/iphone.svg
  week2/dongyun/dummy_assets/perfume.svg
  week2/dongyun/dummy_assets/sandwich.png
  week2/dongyun/dummy_assets/sandwich.svg
  week2/dongyun/index.css
  week2/dongyun/index.html
  week2/dongyun/reset.css
Labels: 강동윤

#30 [2주차] 당근마켓 클론 코딩
  .vscode/launch.json
  week2/sangh2ee/clone/assets/menu.svg
  week2/sangh2ee/clone/assets/notification.svg
  week2/sangh2ee/clone/assets/search.svg
  week2/sangh2ee/clone/clone/index.css
  week2/sangh2ee/clone/clone/index.html
  week2/sangh2ee/clone/clone/reset.css
  week2/sangh2ee/clone/daangn/assets/airpods.svg
  week2/sangh2ee/clone/daangn/assets/airpods_no_radius.svg
  week2/sangh2ee/clone/daangn/assets/byredo.svg
  week2/sangh2ee/clone/daangn/assets/chat.svg
  week2/sangh2ee/clone/daangn/assets/chatting.svg
  week2/sangh2ee/clone/daangn/assets/coffee__machine.svg
  week2/sangh2ee/clone/daangn/assets/expand_arrow_down.svg
  week2/sangh2ee/clone/daangn/assets/heart.svg
  week2/sangh2ee/clone/daangn/assets/home.svg
  week2/sangh2ee/clone/daangn/assets/iphone13__promax.svg
  week2/sangh2ee/clone/daangn/assets/menu.svg
  week2/sangh2ee/clone/daangn/assets/my.svg
  week2/sangh2ee/clone/daangn/assets/near.svg
  week2/sangh2ee/clone/daangn/assets/neighbor.svg
  week2/sangh2ee/clone/daangn/assets/notification.svg
  week2/sangh2ee/clone/daangn/assets/plus__button.svg
  week2/sangh2ee/clone/daangn/assets/sandwich.svg
  week2/sangh2ee/clone/daangn/assets/search.svg
  week2/sangh2ee/clone/daangn/index.css
  week2/sangh2ee/clone/daangn/index.html
Labels: 백상희

#31 [2주차] 당근마켓 클론 코딩
  week2/sunghoJo/assets/airpods-pro.svg
  week2/sunghoJo/assets/byredo-blanche.svg
  week2/sunghoJo/assets/chat.svg
  week2/sunghoJo/assets/coffeemachine.svg
  week2/sunghoJo/assets/dog.svg
  week2/sunghoJo/assets/expand_arrow.svg
  week2/sunghoJo/assets/heart.svg
  week2/sunghoJo/assets/home.svg
  week2/sunghoJo/assets/iPhone13proMax.svg
  week2/sunghoJo/assets/menu.svg
  week2/sunghoJo/assets/news.svg
  week2/sunghoJo/assets/notification.svg
  week2/sunghoJo/assets/place-marker.svg
  week2/sunghoJo/assets/plus-math.svg
  week2/sunghoJo/assets/sandwich.svg
  week2/sunghoJo/assets/search.svg
  week2/sunghoJo/assets/text.svg
  week2/sunghoJo/assets/user.svg
  week2/sunghoJo/index.css
  week2/sunghoJo/index.html
  week2/sunghoJo/reset.css
Labels: 조성호

#26 [2주차]당근마켓1 과제 완성
  week2/jinho1011/clone/index.css
  week2/parktaehee/market_1/assets/50ml.png
  week2/parktaehee/market_1/assets/airpot.png
  week2/parktaehee/market_1/assets/arrow.png
  week2/parktaehee/market_1/assets/coffee.png
  week2/parktaehee/market_1/assets/discuss-line.png
  week2/parktaehee/market_1/assets/heart-line.png
  week2/parktaehee/market_1/assets/iphone.png
  week2/parktaehee/market_1/assets/menu-line.png
  week2/parktaehee/market_1/assets/notice.png
  week2/parktaehee/market_1/assets/sandwich.png
  week2/parktaehee/market_1/assets/search-line.png
  week2/parktaehee/market_1/index.css
  week2/parktaehee/market_1/index.html
  week2/parktaehee/market_1/reset.css
  week2/parktaehee/market_5/assets/heart.svg
  week2/parktaehee/market_5/assets/home.svg
  week2/parktaehee/market_5/assets/kebab.svg
  week2/parktaehee/market_5/assets/left-chevron copy.svg
  week2/parktaehee/market_5/assets/left-chevron.svg
  week2/parktaehee/market_5/assets/right-chevron.svg
  week2/parktaehee/market_5/assets/share.svg
  week2/parktaehee/market_5/index.css
  week2/parktaehee/market_5/index.html
  week2/parktaehee/market_5/reset.css
Labels: 박태희

#29 [2주차] 당근마켓 클론 코딩
  .DS_Store
  week1/.DS_Store
  week1/joshcho/index.html
  week1/junseochoi/index.css
  week2/junseochoi/assets/bottom_chevron.svg
  week2/junseochoi/assets/chat.svg
  week2/junseochoi/assets/chat2.svg
  week2/junseochoi/assets/heart.svg
  week2/junseochoi/assets/home.svg
  week2/junseochoi/assets/menu.svg
  week2/junseochoi/assets/neiborhood.svg
  week2/junseochoi/assets/notofication.svg
  week2/junseochoi/assets/placemarker.svg
  week2/junseochoi/assets/plus.svg
  week2/junseochoi/assets/plusbutton.svg
  week2/junseochoi/assets/search.svg
  week2/junseochoi/assets/user.svg
  week2/junseochoi/index.css
  week2/junseochoi/index.html
  week2/junseochoi/reset.css
Labels: 최준서

#33 [2주차] 당근마켓 제작
  week2/dohyeonKim/assets/bell_icon.svg
  week2/dohyeonKim/assets/chat_icon.svg
  week2/dohyeonKim/assets/expend_arrow.svg
  week2/dohyeonKim/assets/heart_icon.svg
  week2/dohyeonKim/assets/menu_icon.svg
  week2/dohyeonKim/assets/nav_chat.svg
  week2/dohyeonKim/assets/nav_home.svg
  week2/dohyeonKim/assets/nav_news.svg
  week2/dohyeonKim/assets/nav_place.svg
  week2/dohyeonKim/assets/nav_user.svg
  week2/dohyeonKim/assets/plus.svg
  week2/dohyeonKim/assets/product1.png
  week2/dohyeonKim/assets/product2.png
  week2/dohyeonKim/assets/product3.png
  week2/dohyeonKim/assets/product4.png
  week2/dohyeonKim/assets/product5.png
  week2/dohyeonKim/assets/search_icon.svg
  week2/dohyeonKim/index.css
  week2/dohyeonKim/index.html
  week2/dohyeonKim/reset.css
Labels: 김도현2732
