Repository Konkuk-KUIT/KUIT5_WEB-Frontend, pull requests merged in 2025-04, with the labels that each got.

#36 [3주차] TodoList 제작
  week3/TaekyuAhn/index.css
  week3/TaekyuAhn/index.html
  week3/TaekyuAhn/index.js
Labels: 안태규

#37 [3주차] Todo List 제작
  week3/hamxxn/jung-eon/index.css
  week3/hamxxn/jung-eon/index.html
  week3/hamxxn/jung-eon/index.js
Labels: 이정언

#39 [3주차] Todo List 제작
  week3/dohyeonKim/index.css
  week3/dohyeonKim/index.html
  week3/dohyeonKim/index.js
Labels: 김도현2732

#40 [3주차] Todo List 제작
  week3/dhKim/index.css
  week3/dhKim/index.html
  week3/dhKim/index.js
Labels: 김도현3885

#41 [3주차] Todo List 제작
  week3/FEhwan/.vscode/launch.json
  week3/FEhwan/index.css
  week3/FEhwan/index.html
  week3/FEhwan/index.js
  week3/hamxxn/.vscode/launch.json
Labels: 이지환

#42 Parktaehee
  week3/parktaehee/index.css
  week3/parktaehee/index.html
  week3/parktaehee/index.js
Labels: 박태희

#43 [3주차] Todo List 제작
  week2/jungbeen/clone/index.css
  week2/jungbeen/clone/index.html
  week3/jungbeen/index.css
  week3/jungbeen/index.html
  week3/jungbeen/index.js
Labels: 이정빈

#44 [3주차] Todo List 제작
  week3/GahyunKim/edit.svg
  week3/GahyunKim/index.css
  week3/GahyunKim/index.html
  week3/GahyunKim/index.js
Labels: 김가현

#48 [3주차] To-do List 기능 구현
  week3/sunghoJo/index.css
  week3/sunghoJo/index.html
  week3/sunghoJo/index.js
Labels: 조성호

#49 [3주차 과제] Todo List 작성
  week3/lyouxsun/index.css
  week3/lyouxsun/index.html
  week3/lyouxsun/index.js
Labels: 이영선

#52 [4주차] React로 당근마켓 화면 구현
  week4/TaekyuAhn/package-lock.json
  week4/TaekyuAhn/package.json
  week4/TaekyuAhn/public/imgs/bell.svg
  week4/TaekyuAhn/public/imgs/chats.svg
  week4/TaekyuAhn/public/imgs/comments.svg
  week4/TaekyuAhn/public/imgs/down-chevron.svg
  week4/TaekyuAhn/public/imgs/heart.svg
  week4/TaekyuAhn/public/imgs/home.svg
  week4/TaekyuAhn/public/imgs/image1.png
  week4/TaekyuAhn/public/imgs/image2.png
  week4/TaekyuAhn/public/imgs/image3.png
  week4/TaekyuAhn/public/imgs/image4.png
  week4/TaekyuAhn/public/imgs/location.svg
  week4/TaekyuAhn/public/imgs/magnifying-glass.svg
  week4/TaekyuAhn/public/imgs/news.svg
  week4/TaekyuAhn/public/imgs/person.svg
  week4/TaekyuAhn/public/imgs/plus-button.svg
  week4/TaekyuAhn/public/imgs/three-lines.svg
  week4/TaekyuAhn/public/index.html
  week4/TaekyuAhn/src/Home.jsx
  week4/TaekyuAhn/src/components/Item.jsx
  week4/TaekyuAhn/src/components/index.js
  week4/TaekyuAhn/src/index.js
  week4/TaekyuAhn/src/index.module.scss
  week4/TaekyuAhn/src/models/MarketModel.js
Labels: 안태규

#56 [4주차] React로 당근마켓 화면 구현
  week4/jungbeen/package-lock.json
  week4/jungbeen/package.json
  week4/jungbeen/public/index.html
  week4/jungbeen/src/Home.jsx
  week4/jungbeen/src/assets/airpods-pro.svg
  week4/jungbeen/src/assets/byredo-blanche.svg
  week4/jungbeen/src/assets/coffee-machine.svg
  week4/jungbeen/src/assets/expand-arrow.svg
  week4/jungbeen/src/assets/heart.svg
  week4/jungbeen/src/assets/iphone-13-pro-max.svg
  week4/jungbeen/src/assets/menu.svg
  week4/jungbeen/src/assets/nav-chat.svg
  week4/jungbeen/src/assets/nav-home.svg
  week4/jungbeen/src/assets/nav-location.svg
  week4/jungbeen/src/assets/nav-newspaper.svg
  week4/jungbeen/src/assets/nav-person.svg
  week4/jungbeen/src/assets/notification.svg
  week4/jungbeen/src/assets/plus.svg
  week4/jungbeen/src/assets/sales-chat.svg
  week4/jungbeen/src/assets/sandwitch.svg
  week4/jungbeen/src/assets/search.svg
  week4/jungbeen/src/components/BottomNav.jsx
  week4/jungbeen/src/components/Content.jsx
  week4/jungbeen/src/components/Header.jsx
  week4/jungbeen/src/index.css
  week4/jungbeen/src/index.js
  week4/jungbeen/src/models/MarketModel.js
  week4/jungbeen/src/styles/reset.css
Labels: 이정빈

#62 [4주차 미션] 당근마켓 React로 구현하기
  package-lock.json
  package.json
  week2/jinho1011/lecture/index.html
  week4/sunghoJo/package-lock.json
  week4/sunghoJo/package.json
  week4/sunghoJo/public/assets/airpods-pro.svg
  week4/sunghoJo/public/assets/byredo-blanche.svg
  week4/sunghoJo/public/assets/chat.svg
  week4/sunghoJo/public/assets/coffeemachine.svg
  week4/sunghoJo/public/assets/dog.svg
  week4/sunghoJo/public/assets/expand_arrow.svg
  week4/sunghoJo/public/assets/heart.svg
  week4/sunghoJo/public/assets/home.svg
  week4/sunghoJo/public/assets/iPhone13proMax.svg
  week4/sunghoJo/public/assets/menu.svg
  week4/sunghoJo/public/assets/news.svg
  week4/sunghoJo/public/assets/notification.svg
  week4/sunghoJo/public/assets/place-marker.svg
  week4/sunghoJo/public/assets/plus-math.svg
  week4/sunghoJo/public/assets/sandwich.svg
  week4/sunghoJo/public/assets/search.svg
  week4/sunghoJo/public/assets/text.svg
  week4/sunghoJo/public/assets/user.svg
  week4/sunghoJo/public/index.html
  week4/sunghoJo/src/Home.css
  week4/sunghoJo/src/Home.jsx
  week4/sunghoJo/src/components/BottomBar.jsx
  week4/sunghoJo/src/components/Header.jsx
  week4/sunghoJo/src/components/ProductPost.jsx
  week4/sunghoJo/src/index.css
  week4/sunghoJo/src/index.js
  week4/sunghoJo/src/reset.css
Labels: 조성호

#57 Parktaeehee
  week4/Parktaehee/package-lock.json
  week4/Parktaehee/package.json
  week4/Parktaehee/public/assets/add.svg
  week4/Parktaehee/public/assets/airpods-pro.png
  week4/Parktaehee/public/assets/arrow.svg
  week4/Parktaehee/public/assets/byredo-blanche.png
  week4/Parktaehee/public/assets/chat.svg
  week4/Parktaehee/public/assets/coffee-machine.png
  week4/Parktaehee/public/assets/heart.svg
  week4/Parktaehee/public/assets/home.svg
  week4/Parktaehee/public/assets/iphone-13-pro-max.png
  week4/Parktaehee/public/assets/life.svg
  week4/Parktaehee/public/assets/location.svg
  week4/Parktaehee/public/assets/menu-line.svg
  week4/Parktaehee/public/assets/my.svg
  week4/Parktaehee/public/assets/notice.svg
  week4/Parktaehee/public/assets/sandwich.png
  week4/Parktaehee/public/assets/search.svg
  week4/Parktaehee/public/assets/write.svg
  week4/Parktaehee/public/index.html
  week4/Parktaehee/src/Home.css
  week4/Parktaehee/src/Home.jsx
  week4/Parktaehee/src/components/BottomNav.jsx
  week4/Parktaehee/src/components/Content.jsx
  week4/Parktaehee/src/components/Header.jsx
  week4/Parktaehee/src/index.js
  week4/Parktaehee/src/models/MarketModel.js
Labels: 박태희

#53 [4주차] react로 당근마켓 화면 구현
  week4/dohyeonKim/package-lock.json
  week4/dohyeonKim/package.json
  week4/dohyeonKim/public/assets/airpods-pro.png
  week4/dohyeonKim/public/assets/bell_icon.svg
  week4/dohyeonKim/public/assets/byredo-blanche.png
  week4/dohyeonKim/public/assets/chat_icon.svg
  week4/dohyeonKim/public/assets/coffee-machine.png
  week4/dohyeonKim/public/assets/expend_arrow.svg
  week4/dohyeonKim/public/assets/heart_icon.svg
  week4/dohyeonKim/public/assets/iphone-13-pro-max.png
  week4/dohyeonKim/public/assets/menu_icon.svg
  week4/dohyeonKim/public/assets/nav_chat.svg
  week4/dohyeonKim/public/assets/nav_home.svg
  week4/dohyeonKim/public/assets/nav_news.svg
  week4/dohyeonKim/public/assets/nav_place.svg
  week4/dohyeonKim/public/assets/nav_user.svg
  week4/dohyeonKim/public/assets/plus.svg
  week4/dohyeonKim/public/assets/sandwich.png
  week4/dohyeonKim/public/assets/search_icon.svg
  week4/dohyeonKim/public/index.html
  week4/dohyeonKim/src/Home.jsx
  week4/dohyeonKim/src/components/BottomNav.jsx
  week4/dohyeonKim/src/components/Content.jsx
  week4/dohyeonKim/src/components/Header.jsx
  week4/dohyeonKim/src/index.css
  week4/dohyeonKim/src/index.js
  week4/dohyeonKim/src/models/MarketModel.js
  week4/ho0010/public/assets/heart.svg
  week4/ho0010/public/assets/left-chevron.svg
Labels: 김도현2732

#59 4주차 당근마켓 클론코딩 React 이식
  week4/dongyun/.gitignore
  week4/dongyun/README.md
  week4/dongyun/eslint.config.js
  week4/dongyun/index.html
  week4/dongyun/package-lock.json
  week4/dongyun/package.json
  week4/dongyun/public/assets/carrotIcon.png
  week4/dongyun/public/assets/chatting_icon.svg
  week4/dongyun/public/assets/expand_arrow.svg
  week4/dongyun/public/assets/heart_icon.svg
  week4/dongyun/public/assets/home_btn_icon.svg
  week4/dongyun/public/assets/location_marker_icon.svg
  week4/dongyun/public/assets/menu_btn.svg
  week4/dongyun/public/assets/notification_icon.svg
  week4/dongyun/public/assets/offer_chat_count_icon.svg
  week4/dongyun/public/assets/plus_icon.svg
  week4/dongyun/public/assets/posting_icon.svg
  week4/dongyun/public/assets/profile_icon.svg
  week4/dongyun/public/assets/search_btn.svg
  week4/dongyun/public/assets/villiage_news_icon.svg
  week4/dongyun/public/dummy_assets/MarketModel.js
  week4/dongyun/public/dummy_assets/airpot.png
  week4/dongyun/public/dummy_assets/airpot.svg
  week4/dongyun/public/dummy_assets/coffeeTool.svg
  week4/dongyun/public/dummy_assets/computerBook.svg
  week4/dongyun/public/dummy_assets/iphone.svg
  week4/dongyun/public/dummy_assets/macbook.svg
  week4/dongyun/public/dummy_assets/perfume.svg
  week4/dongyun/public/dummy_assets/sandwich.png
  week4/dongyun/public/dummy_assets/sandwich.svg
  week4/dongyun/src/Home.css
  week4/dongyun/src/Home.jsx
  week4/dongyun/src/components/LowerNav.jsx
  week4/dongyun/src/components/Market.jsx
  week4/dongyun/src/components/MarketItem.jsx
  week4/dongyun/src/components/PostingBtn.jsx
  week4/dongyun/src/components/UpperNav.css
  week4/dongyun/src/components/UpperNav.jsx
  week4/dongyun/src/index.css
  week4/dongyun/src/main.jsx
  week4/dongyun/vite.config.js
  week4/ho0010/.DS_Store
Labels: 강동윤

#47 [3주차] Todo List 제작
  .gitignore
  week2/jungbeen/clone/index.css
  week3/sangh2ee/index.css
  week3/sangh2ee/index.html
  week3/sangh2ee/index.js
Labels: 백상희

#66 [4주차] React로 당근마켓 화면 구현 재PR
  week4/junseochoi/package-lock.json
  week4/junseochoi/package.json
  week4/junseochoi/public/assets/bottom_chevron.svg
  week4/junseochoi/public/assets/chat.svg
  week4/junseochoi/public/assets/chat2.svg
  week4/junseochoi/public/assets/heart.svg
  week4/junseochoi/public/assets/home.svg
  week4/junseochoi/public/assets/menu.svg
  week4/junseochoi/public/assets/neiborhood.svg
  week4/junseochoi/public/assets/notofication.svg
  week4/junseochoi/public/assets/placemarker.svg
  week4/junseochoi/public/assets/plus.svg
  week4/junseochoi/public/assets/plusbutton.svg
  week4/junseochoi/public/assets/search.svg
  week4/junseochoi/public/assets/user.svg
  week4/junseochoi/public/index.html
  week4/junseochoi/src/Home.css
  week4/junseochoi/src/Home.jsx
  week4/junseochoi/src/components/BottomNav.jsx
  week4/junseochoi/src/components/Content.jsx
  week4/junseochoi/src/components/Header.jsx
  week4/junseochoi/src/components/index.js
  week4/junseochoi/src/index.js
  week4/junseochoi/src/models/MarketModel.js
Labels: 최준서
