Repository Konkuk-KUIT/KUIT5_WEB-Frontend, pull requests merged in 2025-06, with the labels that each got.

#110 [9주차] Typescript
  week9/lyouxsun/hw/.gitignore
  week9/lyouxsun/hw/package-lock.json
  week9/lyouxsun/hw/package.json
  week9/lyouxsun/hw/public/assets/1.png
  week9/lyouxsun/hw/public/assets/2.png
  week9/lyouxsun/hw/public/assets/3.png
  week9/lyouxsun/hw/public/assets/4.png
  week9/lyouxsun/hw/public/assets/5.png
  week9/lyouxsun/hw/public/assets/back.png
  week9/lyouxsun/hw/public/favicon.ico
  week9/lyouxsun/hw/public/index.html
  week9/lyouxsun/hw/src/App.js
  week9/lyouxsun/hw/src/App.tsx
  week9/lyouxsun/hw/src/components/Card.styles.tsx
  week9/lyouxsun/hw/src/components/CardContainer.tsx
  week9/lyouxsun/hw/src/components/FlipCard.tsx
  week9/lyouxsun/hw/src/components/ResetButton.tsx
  week9/lyouxsun/hw/src/components/Score.tsx
  week9/lyouxsun/hw/src/data.js
  week9/lyouxsun/hw/src/data.ts
  week9/lyouxsun/hw/src/hooks/useFlip.js
  week9/lyouxsun/hw/src/hooks/useFlip.ts
  week9/lyouxsun/hw/src/index.tsx
  week9/lyouxsun/hw/src/main.jsx
  week9/lyouxsun/hw/tsconfig.json
Labels: 이영선

#113 [9주차] TypeScript
  package.json
  tests-examples/demo-todo-app.spec.ts
  week8/jung-eon/db.json
  week9/jung-eon/todo/app.js
  week9/jung-eon/todo/app.ts
  week9/jung-eon/todo/db.json
  week9/jung-eon/todo/index.css
  week9/jung-eon/todo/index.html
  week9/jung-eon/todo/tsconfig.json
  week9/jung-eon/week4_ts/assets/bx_chat.svg
  week9/jung-eon/week4_ts/assets/chat-img.svg
  week9/jung-eon/week4_ts/assets/expand-arrow.svg
  week9/jung-eon/week4_ts/assets/heart.svg
  week9/jung-eon/week4_ts/assets/home-img.svg
  week9/jung-eon/week4_ts/assets/menu1.svg
  week9/jung-eon/week4_ts/assets/news-img.svg
  week9/jung-eon/week4_ts/assets/notification1.svg
  week9/jung-eon/week4_ts/assets/place-marker-img.svg
  week9/jung-eon/week4_ts/assets/plus-button.svg
  week9/jung-eon/week4_ts/assets/post-header__bottom.svg
  week9/jung-eon/week4_ts/assets/post__img1.svg
  week9/jung-eon/week4_ts/assets/post__img2.svg
  week9/jung-eon/week4_ts/assets/post__img3.svg
  week9/jung-eon/week4_ts/assets/post__img4.svg
  week9/jung-eon/week4_ts/assets/post__img5.svg
  week9/jung-eon/week4_ts/assets/search.svg
  week9/jung-eon/week4_ts/assets/user-img.svg
  week9/jung-eon/week4_ts/index.html
  week9/jung-eon/week4_ts/package-lock.json
  week9/jung-eon/week4_ts/package.json
  week9/jung-eon/week4_ts/src/Home.tsx
  week9/jung-eon/week4_ts/src/components/BottomNav.tsx
  week9/jung-eon/week4_ts/src/components/Content.tsx
  week9/jung-eon/week4_ts/src/components/Header.tsx
  week9/jung-eon/week4_ts/src/index.css
  week9/jung-eon/week4_ts/src/index.tsx
  week9/jung-eon/week4_ts/src/models/MarketModels.ts
  week9/jung-eon/week4_ts/tsconfig.app.json
  week9/jung-eon/week4_ts/tsconfig.json
  week9/jung-eon/week4_ts/tsconfig.node.json
  week9/jung-eon/week4_ts/vite.config.ts
Labels: 이정언

#114 [9주차] TypeScript
  week8/junseochoi/db.json
  week9/junseochoi/.gitignore
  week9/junseochoi/README.md
  week9/junseochoi/package-lock.json
  week9/junseochoi/package.json
  week9/junseochoi/public/index.html
  week9/junseochoi/src/App.js
  week9/junseochoi/src/App.tsx
  week9/junseochoi/src/assets/Back.png
  week9/junseochoi/src/assets/Eevee.png
  week9/junseochoi/src/assets/Fairy.png
  week9/junseochoi/src/assets/Fire.png
  week9/junseochoi/src/assets/Ice.png
  week9/junseochoi/src/assets/Leaf.png
  week9/junseochoi/src/assets/types/images.d.ts
  week9/junseochoi/src/components/Card/Card.Styled.ts
  week9/junseochoi/src/components/Card/Card.tsx
  week9/junseochoi/src/components/Count/Count.js
  week9/junseochoi/src/components/Count/Count.tsx
  week9/junseochoi/src/components/ResetBtn/ResetBtn.tsx
  week9/junseochoi/src/index.js
  week9/junseochoi/src/models/CardList.js
  week9/junseochoi/src/models/CardList.tsx
  week9/junseochoi/tsconfig.json
Labels: 최준서

#115 [9주차] Typescript
  week9/dongyun/.gitignore
  week9/dongyun/README.md
  week9/dongyun/db.json
  week9/dongyun/eslint.config.js
  week9/dongyun/index.html
  week9/dongyun/package-lock.json
  week9/dongyun/package.json
  week9/dongyun/public/public_assets/arrow-front-icon.svg
  week9/dongyun/public/public_assets/backButton.svg
  week9/dongyun/public/public_assets/blanked-star.svg
  week9/dongyun/public/public_assets/blue-plus-icon.svg
  week9/dongyun/public/public_assets/filled-star.svg
  week9/dongyun/public/public_assets/pizzaIcon.svg
  week9/dongyun/public/public_assets/warning-icon.svg
  week9/dongyun/src/apis/cart-list.ts
  week9/dongyun/src/apis/food-category.ts
  week9/dongyun/src/apis/store-list.ts
  week9/dongyun/src/apis/store-menu.ts
  week9/dongyun/src/components/cart/Cart.style.tsx
  week9/dongyun/src/components/cart/CartCard.style.tsx
  week9/dongyun/src/components/cart/CartCard.tsx
  week9/dongyun/src/components/home/FoodCategory.tsx
  week9/dongyun/src/components/home/FoodCell.style.tsx
  week9/dongyun/src/components/home/FoodCell.tsx
  week9/dongyun/src/components/home/GreetingPage.style.tsx
  week9/dongyun/src/components/home/GreetingPage.tsx
  week9/dongyun/src/components/home/Home.styles.tsx
  week9/dongyun/src/components/shared/HomeIndicator.tsx
  week9/dongyun/src/components/shared/OrderFooter.style.tsx
  week9/dongyun/src/components/shared/OrderFooter.tsx
  week9/dongyun/src/components/shared/SectionHeader.style.tsx
  week9/dongyun/src/components/shared/SectionHeader.tsx
  week9/dongyun/src/components/store-menu/StoreInfo.style.tsx
  week9/dongyun/src/components/store-menu/StoreInfo.tsx
  week9/dongyun/src/components/store-menu/StoreMenuCard.style.tsx
  week9/dongyun/src/components/store-menu/StoreMenuCard.tsx
  week9/dongyun/src/components/stores/StoreRankingCard.style.tsx
  week9/dongyun/src/components/stores/StoreRankingCard.tsx
  week9/dongyun/src/index.css
  week9/dongyun/src/main.tsx
  week9/dongyun/src/routes/Cart.tsx
  week9/dongyun/src/routes/Home.tsx
  week9/dongyun/src/routes/StoreMenu.tsx
  week9/dongyun/src/routes/Stores.tsx
  week9/dongyun/src/types/types.ts
  week9/dongyun/src/vite-env.d.ts
  week9/dongyun/tsconfig.app.json
  week9/dongyun/tsconfig.json
  week9/dongyun/tsconfig.node.json
  week9/dongyun/vite.config.ts
Labels: 강동윤

#117 [9주차] Typescript
  week3/FEhwan/index.ts
  week9/FEhwan/.vscode/launch.json
  week9/FEhwan/index.css
  week9/FEhwan/index.html
  week9/FEhwan/index.ts
Labels: 이지환

#118 [9주차] Typescript
  week9/gahyun/.gitignore
  week9/gahyun/README.md
  week9/gahyun/db.json
  week9/gahyun/package-lock.json
  week9/gahyun/package.json
  week9/gahyun/public/favicon.ico
  week9/gahyun/public/index.html
  week9/gahyun/public/logo192.png
  week9/gahyun/public/logo512.png
  week9/gahyun/public/manifest.json
  week9/gahyun/public/robots.txt
  week9/gahyun/src/App.js
  week9/gahyun/src/components/AddStoreForm.jsx
  week9/gahyun/src/components/BottomBar.jsx
  week9/gahyun/src/components/Button.jsx
  week9/gahyun/src/components/Category.jsx
  week9/gahyun/src/components/Category.styles.jsx
  week9/gahyun/src/components/OrderBar.jsx
  week9/gahyun/src/components/PriceContainer.jsx
  week9/gahyun/src/components/StoreDetail.tsx
  week9/gahyun/src/components/StoreList.tsx
  week9/gahyun/src/components/StoresDetail.jsx
  week9/gahyun/src/components/StoresList.jsx
  week9/gahyun/src/components/StoresTemp.jsx
  week9/gahyun/src/fonts/Pretendard-Bold.woff2
  week9/gahyun/src/fonts/Pretendard-Regular.woff2
  week9/gahyun/src/fonts/fonts.css
  week9/gahyun/src/images.d.ts
  week9/gahyun/src/index.js
  week9/gahyun/src/models/arrow.svg
  week9/gahyun/src/models/arrowBack.svg
  week9/gahyun/src/models/plus.svg
  week9/gahyun/src/models/star.svg
  week9/gahyun/src/models/stores.js
  week9/gahyun/src/models/warning.svg
  week9/gahyun/src/pages/Cart.jsx
  week9/gahyun/src/pages/Home.jsx
  week9/gahyun/src/pages/Router.jsx
  week9/gahyun/src/pages/Store.jsx
  week9/gahyun/src/pages/Stores.jsx
  week9/gahyun/src/styles/GlobalStyles.js
  week9/gahyun/src/styles/Header.styles.jsx
  week9/gahyun/src/styles/Home.styles.jsx
  week9/gahyun/src/styles/TopBar.styles.jsx
Labels: 김가현

#119 [9주차] TypeScript
  package-lock.json
  week7/joshcho/src/index.js
  week9/joshcho/.gitignore
  week9/joshcho/README.md
  week9/joshcho/db.json
  week9/joshcho/package-lock.json
  week9/joshcho/package.json
  week9/joshcho/public/favicon.ico
  week9/joshcho/public/index.html
  week9/joshcho/public/logo192.png
  week9/joshcho/public/logo512.png
  week9/joshcho/public/manifest.json
  week9/joshcho/public/robots.txt
  week9/joshcho/src/App.js
  week9/joshcho/src/App.tsx
  week9/joshcho/src/apis/post.js
  week9/joshcho/src/components/ActionButton.styles.tsx
  week9/joshcho/src/components/ActionButton.tsx
  week9/joshcho/src/components/BottomOrderBar.tsx
  week9/joshcho/src/components/Button.tsx
  week9/joshcho/src/components/GlobalStyle.tsx
  week9/joshcho/src/components/GoBack.tsx
  week9/joshcho/src/components/Input.styles.tsx
  week9/joshcho/src/components/Input.tsx
  week9/joshcho/src/components/MenuList.tsx
  week9/joshcho/src/components/OrderList.tsx
  week9/joshcho/src/components/Rectangle.tsx
  week9/joshcho/src/components/StoreList.tsx
  week9/joshcho/src/components/Title.tsx
  week9/joshcho/src/img/chicken.svg
  week9/joshcho/src/img/coffee.svg
  week9/joshcho/src/img/dessert.svg
  week9/joshcho/src/img/hamburger.svg
  week9/joshcho/src/img/koreanFood.svg
  week9/joshcho/src/img/left_chevron.svg
  week9/joshcho/src/img/pasta.svg
  week9/joshcho/src/img/pizza.svg
  week9/joshcho/src/img/plus.svg
  week9/joshcho/src/img/right_chevron.svg
  week9/joshcho/src/img/salad.svg
  week9/joshcho/src/img/sandwich.svg
  week9/joshcho/src/img/seeMore.svg
  week9/joshcho/src/img/snackFood.svg
  week9/joshcho/src/img/star.svg
  week9/joshcho/src/img/sushi.svg
  week9/joshcho/src/img/warn.svg
  week9/joshcho/src/index.ts
  week9/joshcho/src/models/RectangleList.tsx
  week9/joshcho/src/pages/Cart.styles.tsx
  week9/joshcho/src/pages/Cart.tsx
  week9/joshcho/src/pages/Home.styles.tsx
  week9/joshcho/src/pages/Home.tsx
  week9/joshcho/src/pages/Router.tsx
  week9/joshcho/src/pages/Store.tsx
  week9/joshcho/src/pages/Stores.styles.tsx
  week9/joshcho/src/pages/Stores.tsx
  week9/joshcho/src/svg.d.ts
  week9/joshcho/tsconfig.json
Labels: 조성호
